// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("3.0.2")]
[assembly: AssemblyFileVersionAttribute("3.0.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.2";
    }
}
