// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("2.0.5")]
[assembly: AssemblyFileVersionAttribute("2.0.5")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.5";
    }
}
