// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("3.0.1")]
[assembly: AssemblyFileVersionAttribute("3.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.1";
    }
}
